/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build`.
// It's included here so the project has valid TS types out of the box;
// Next.js will overwrite it automatically on first run.
